### ISSUE TITLE
Search by commit instead of dates

### ISSUE THREAD

**Issue by flacle** [flacle/truegitcodechurn#11]
Search by commit would probably be optional arguments.

- There are two arguments, start and end commit hashes.
- Search by default is the short hash, any hash longer than this gets truncated to its short version, any hash shorter than this gets an error message.
- If the timestamps of the start and end commits are not in order (reversed, equal) then the order has to be fixed, in case the same commit is used for both start and end date then the git command should just take one hash.
- The optional commit arguments should override the positional dates arguments.

Reference: #10

**Comment by JonathanGuerne** [comment]
If it's ok for you I'd like to try to solve this issue

**Comment by flacle** [comment]
@JonathanGuerne great, any help is appreciated. Would recommend though to keep the scope tight, any new issues/request that you stumble upon can be solved via separate tickets, this makes review/testing more efficient. Perhaps after the release I can help with #9, this will make the codebase more friendly to include in other workflows/pipelines.

**Comment by JonathanGuerne** [comment]
I submitted a PR (https://github.com/flacle/truegitcodechurn/pull/12) 
As you asked a focused only on the issue mentioned here.

**Comment by flacle** [comment]
Hi @JonathanGuerne I'm waiting to get a new machine sometime this week, will then be able to finally review your PR. Thanks for your patience.

**Comment by JonathanGuerne** [comment]
Hi sorry to have taken so long to get back to you. 

No worries take all the time you need for the review
